services:
  postgres_db:
    image: postgres:15
    container_name: postgres_univer_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: postgres_univer_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres_univer_db"]
      timeout: 30s
      interval: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

